MaxPQ: MaxPriorityQueue.o  main.c MaxPriorityQueue.h
	g++ -o MAXPQ MaxPriorityQueue.o main.c

MaxPriorityQueue.o: MaxPriorityQueue.cpp MaxPriorityQueue.h
	g++ -c MaxPriorityQueue.cpp

clean:
	rm *.o

